### ISSUE TITLE
Testcase is not stopping.

### ISSUE THREAD

**Issue by gtilg** [patmalcolm91/cell-transmission-model#3]
Even though the end_time is set to 24, the simulation runs until "27:24:00", and then starts to through errors.
![test_ctm](https://user-images.githubusercontent.com/49945486/114838894-72875a00-9dd5-11eb-8599-327fa445a1aa.PNG)

**Comment by patmalcolm91** [comment]
The current time_step property is decoupled from the actual ``Simulation.step()`` method, which could lead to off-by-one errors due to floating point precision errors. This should be refactored.

In addition, a better API for running simulations and showing animations/results should be implemented.
